### ISSUE TITLE
[1.15.1] Missing Textures in JEI/Creative Mode

### ISSUE THREAD

**Issue by realTIMematrix** [SkyNetCloud/CyberCore_Mod#3]
Hi,

I miss some textures in the core mod:

cybercore:cheese
cybercore:taco
cybercore:lettuce
cybercore:tomato
cybercore:block_pipe (Item Conduit)

Using forge-30.0.41

**Comment by SkyNetCloud** [comment]
Oh Ik there Missing Textures I just forgot to set up the item JSON file for them should be fixed in the next update sorry for that my dude

**Comment by SkyNetCloud** [comment]
This will be fixed in 0.7.18362
