### ISSUE TITLE
Failed rendering screen

### ISSUE THREAD

**Issue by KilluaZoldyck77** [SkyNetCloud/CyberCore_Mod#4]
Hi, the mod works well but if i go into creative and I scroll to the mod page it crashes and says "failed rendering screen"

**Comment by SkyNetCloud** [comment]
would you mind giving me the version your using at the time of this

**Comment by SkyNetCloud** [comment]
Ok that will be fixed in the 1.15.2 version update so give me time

**Comment by SkyNetCloud** [comment]
Fix In Update

**Comment by KilluaZoldyck77** [comment]
the last version of the mod and the minecraft 1.15.1

**Comment by KilluaZoldyck77** [comment]
> Fix In Update

ok! Thank you! ^^
