### ISSUE TITLE
Green Ingots have issues....

### ISSUE THREAD

**Issue by jcain341** [SkyNetCloud/CyberCore_Mod#5]
To Whom It May Concern,

I ran into an issue while trying to build tools with your green ingots. Your ruby and your Black steel work but not your green ingots in the last update. Will you be removing that ore or rename it? Anyway, that is the only issue I ran into with your mod. For the record I am using Forge 31.1.18 and playing Minecraft 1.15.2.

CyberJJC

**Comment by SkyNetCloud** [comment]
I will get to work on that asap

**Comment by SkyNetCloud** [comment]
has been fixed in version 1.4 so I'm now closing this
